const reportData = [
  {
    id: "01",
    Name: "abc xyz",
    phone: "5684236527",
    reportDate: "MM/DD/YYYY",
    reportAgainst: "User",
    status: "active",
  },
  {
    id: "02",
    Name: "abc xyz",
    phone: "5684236527",
    reportDate: "MM/DD/YYYY",
    reportAgainst: "User",
    status: "active",
  },
  {
    id: "03",
    Name: "abc xyz",
    phone: "5684236527",
    reportDate: "MM/DD/YYYY",
    reportAgainst: "Post",
    status: "active",
  },
  {
    id: "04",
    Name: "abc xyz",
    phone: "5684236527",
    reportDate: "MM/DD/YYYY",
    reportAgainst: "User",
    status: "active",
  },
  {
    id: "05",
    Name: "abc xyz",
    phone: "5684236527",
    reportDate: "MM/DD/YYYY",
    reportAgainst: "Post",
    status: "active",
  },
  {
    id: "06",
    Name: "abc xyz",
    phone: "5684236527",
    reportDate: "MM/DD/YYYY",
    reportAgainst: "User",
    status: "active",
  },
  {
    id: "07",
    Name: "abc xyz",
    phone: "5684236527",
    reportDate: "MM/DD/YYYY",
    reportAgainst: "User",
    status: "active",
  },
  {
    id: "08",
    Name: "abc xyz",
    phone: "5684236527",
    reportDate: "MM/DD/YYYY",
    reportAgainst: "Post",
    status: "active",
  },
  {
    id: "09",
    Name: "abc xyz",
    phone: "5684236527",
    reportDate: "MM/DD/YYYY",
    reportAgainst: "User",
    status: "active",
  },
  {
    id: "10",
    Name: "abc xyz",
    phone: "5684236527",
    reportDate: "MM/DD/YYYY",
    reportAgainst: "User",
    status: "active",
  },
  {
    id: "11",
    Name: "abc xyz",
    phone: "5684236527",
    reportDate: "MM/DD/YYYY",
    reportAgainst: "Post",
    status: "active",
  },
  {
    id: "12",
    Name: "abc xyz",
    phone: "5684236527",
    reportDate: "MM/DD/YYYY",
    reportAgainst: "User",
    status: "active",
  },
  {
    id: "13",
    Name: "abc xyz",
    phone: "5684236527",
    reportDate: "MM/DD/YYYY",
    reportAgainst: "Post",
    status: "active",
  },
  {
    id: "14",
    Name: "abc xyz",
    phone: "5684236527",
    reportDate: "MM/DD/YYYY",
    reportAgainst: "User",
    status: "active",
  },
  {
    id: "15",
    Name: "abc xyz",
    phone: "5684236527",
    reportDate: "MM/DD/YYYY",
    reportAgainst: "Post",
    status: "active",
  },
  {
    id: "16",
    Name: "abc xyz",
    phone: "5684236527",
    reportDate: "MM/DD/YYYY",
    reportAgainst: "User",
    status: "active",
  },
  {
    id: "17",
    Name: "abc xyz",
    phone: "5684236527",
    reportDate: "MM/DD/YYYY",
    reportAgainst: "Post",
    status: "active",
  },
  {
    id: "18",
    Name: "abc xyz",
    phone: "5684236527",
    reportDate: "MM/DD/YYYY",
    reportAgainst: "User",
    status: "active",
  },
  {
    id: "19",
    Name: "abc xyz",
    phone: "5684236527",
    reportDate: "MM/DD/YYYY",
    reportAgainst: "post",
    status: "active",
  },
  {
    id: "20",
    Name: "abc xyz",
    phone: "5684236527",
    reportDate: "MM/DD/YYYY",
    reportAgainst: "User",
    status: "active",
  },
  {
    id: "21",
    Name: "abc xyz",
    phone: "5684236527",
    reportDate: "MM/DD/YYYY",
    reportAgainst: "Post",
    status: "active",
  },
  {
    id: "22",
    Name: "abc xyz",
    phone: "5684236527",
    reportDate: "MM/DD/YYYY",
    reportAgainst: "User",
    status: "active",
  },
  {
    id: "23",
    Name: "abc xyz",
    phone: "5684236527",
    reportDate: "MM/DD/YYYY",
    reportAgainst: "Post",
    status: "active",
  },
  {
    id: "24",
    Name: "abc xyz",
    phone: "5684236527",
    reportDate: "MM/DD/YYYY",
    reportAgainst: "User",
    status: "active",
  },
  {
    id: "25",
    Name: "abc xyz",
    phone: "5684236527",
    reportDate: "MM/DD/YYYY",
    reportAgainst: "User",
    status: "active",
  },
];

export default reportData;
